SELECT [hashID]
      ,[Geboortemaand]
      ,[Geboortejaar]
      ,[Geslacht]
      ,[Herkomst]
      ,[Nationaliteit]
      ,[Leerling Belgische nationaliteit]
      ,[Autochtoon]
      ,[Thuistaal]
      ,[Moedertaal]
      ,[Beroep moeder]
      ,[Beroep vader]
      ,[Opleiding moeder]
      ,[Burgelijke staat moeder]
      ,[Burgelijke staat vader]
      ,[Moeder overleden]
      ,[Vader overleden]
      ,[Nationaliteit moeder]
      ,[Moeder Belgische nationaliteit]
      ,[Nationaliteit vader]
      ,[Vader Belgische nationaliteit]
      ,[Moeder - Nederlandstalig]
      ,[Moeder - Franstalig]
      ,[Moeder - Anderstalig (niet N/F)]
      ,[Moeder - Geen info over taal]
      ,[Vader - Nederlandstalig]
      ,[Vader - Franstalig]
      ,[Vader - Anderstalig (niet N/F)]
      ,[Vader - Geen info over taal]
      ,[Broer/zus - Nederlandstalig]
      ,[Broer/zus - Franstalig]
      ,[Broer/zus - Anderstalig (niet N/F)]
      ,[Broer/zus - Geen info over taal]
      ,[Vrienden - Nederlandstalig]
      ,[Vrienden - Franstalig]
      ,[Vrienden - Anderstalig (niet N/F)]
      ,[Vrienden - Geen info over taal]
      ,[Moeder - Lager onderwijs niet afgewerkt]
      ,[Moeder - Lager onderwijs afgewerkt]
      ,[Moeder - Lager secundair onderwijs afgewerkt]
      ,[Moeder - Hoger secundair onderwijs afgewerkt]
      ,[Moeder - Hoger onderwijs afgewerkt]
      ,[Moeder - Laag geschoold]
      ,[Thuistaal niet-Nederlands]
      ,[Loopbaan van]
      ,[Loopbaan tot]
      ,[Datum uitschrijving]
      ,[Klas]
      ,[Schooljaar]
      ,[Begin Schooljaar]
      ,[Leerjaar]
      ,[Graad]
      ,[Andertalige nieuwkomer]
      ,[Attest]
      ,[Attest aangepast]
      ,[Clausulering]
      ,[Datum uitreiking]
      ,[Basisonderwijs NL]
      ,[Omschrijving berekening]
      ,[Instelling]
      ,[Type evaluatie]
      ,[Aantal periodes]
      ,[Administratieve groep kort]
      ,[Administratieve groep volledig]
      ,[Domein]
      ,[Finaliteit]
      ,[LeerjaarInGraad]
      ,[Onderwijsvorm]
      ,[Soortleerjaar]
      ,[Stemcategorie]
      ,[Studiegebied]
      ,[Studierichting]
      ,[LeerjaarCijfer]
      ,[Schoolse achterstand]
      ,[Laatste login]
      ,[Aantal dagen geleden]
      ,[Wie laatst ingelogd]
      ,[Verschillende adressen]
      ,[Deelgemeente officieel adres]
      ,[Hoofdgemeente officeel adres]
      ,[Postcode officieel adres]
      ,[AF.']
      ,[AF.-]
      ,[AF.#]
      ,[AF..]
      ,[AF.?]
      ,[AF.+]
      ,[AF.°]
      ,[AF.1]
      ,[AF.2]
      ,[AF.3]
      ,[AF.4]
      ,[AF.5]
      ,[AF.6]
      ,[AF.7]
      ,[AF.8]
      ,[AF.9]
      ,[AF.0]
      ,[AF.A]
      ,[AF.B]
      ,[AF.C]
      ,[AF.D]
      ,[AF.E]
      ,[AF.F]
      ,[AF.G]
      ,[AF.H]
      ,[AF.I]
      ,[AF.J]
      ,[AF.K]
      ,[AF.L]
      ,[AF.M]
      ,[AF.N]
      ,[AF.O]
      ,[AF.P]
      ,[AF.Q]
      ,[AF.R]
      ,[AF.S]
      ,[AF.T]
      ,[AF.U]
      ,[AF.V]
      ,[AF.W]
      ,[AF.X]
      ,[AF.Y]
      ,[AF.Z]
      ,[AF.WE]
      ,[AF.VA]
      ,[AF.SV]
      ,[AF.ST]
      ,[AF.OL]
      ,[AF.KR]
      ,[AF.HL]
      ,[AF.H1]
      ,[AF.EX]
      ,[AF.WO]
      ,[AF.Totaal]
      ,[Vorige school]
      ,[Vorige klas]
      ,[Vorige loopbaan tot]
      ,[Lagere school]
      ,[Laaste leerjaar in lagere school]
      ,[Verandering klas tijdens schooljaar]
      ,[Zij-instromer school tijdens schooljaar]
      ,[Instroom in school bij begin schooljaar]
      ,[Intern]
      ,[Internaat]
      ,SUM(CASE WHEN procent < 50 THEN 1 ELSE 0 END) AS [onder 50%]
	  ,SUM(CASE WHEN procent >= 50 AND procent < 60 THEN 1 ELSE 0 END) AS [tussen 50% en 60%]
      ,SUM(CASE WHEN procent >= 60 THEN 1 ELSE 0 END) AS [boven 60%]
	  ,Count(*) as [Totaal aantal vakken]
	  
  FROM [WiseZonderFK].[dbo].[SJI - Overzicht zonder leerkrachten]

  GROUP BY 
	[hashID]
      ,[Geboortemaand]
      ,[Geboortejaar]
      ,[Geslacht]
      ,[Herkomst]
      ,[Nationaliteit]
      ,[Leerling Belgische nationaliteit]
      ,[Autochtoon]
      ,[Thuistaal]
      ,[Moedertaal]
      ,[Beroep moeder]
      ,[Beroep vader]
      ,[Opleiding moeder]
      ,[Burgelijke staat moeder]
      ,[Burgelijke staat vader]
      ,[Moeder overleden]
      ,[Vader overleden]
      ,[Nationaliteit moeder]
      ,[Moeder Belgische nationaliteit]
      ,[Nationaliteit vader]
      ,[Vader Belgische nationaliteit]
      ,[Moeder - Nederlandstalig]
      ,[Moeder - Franstalig]
      ,[Moeder - Anderstalig (niet N/F)]
      ,[Moeder - Geen info over taal]
      ,[Vader - Nederlandstalig]
      ,[Vader - Franstalig]
      ,[Vader - Anderstalig (niet N/F)]
      ,[Vader - Geen info over taal]
      ,[Broer/zus - Nederlandstalig]
      ,[Broer/zus - Franstalig]
      ,[Broer/zus - Anderstalig (niet N/F)]
      ,[Broer/zus - Geen info over taal]
      ,[Vrienden - Nederlandstalig]
      ,[Vrienden - Franstalig]
      ,[Vrienden - Anderstalig (niet N/F)]
      ,[Vrienden - Geen info over taal]
      ,[Moeder - Lager onderwijs niet afgewerkt]
      ,[Moeder - Lager onderwijs afgewerkt]
      ,[Moeder - Lager secundair onderwijs afgewerkt]
      ,[Moeder - Hoger secundair onderwijs afgewerkt]
      ,[Moeder - Hoger onderwijs afgewerkt]
      ,[Moeder - Laag geschoold]
      ,[Thuistaal niet-Nederlands]
      ,[Loopbaan van]
      ,[Loopbaan tot]
      ,[Datum uitschrijving]
      ,[Klas]
      ,[Schooljaar]
      ,[Begin Schooljaar]
      ,[Leerjaar]
      ,[Graad]
      ,[Andertalige nieuwkomer]
      ,[Attest]
      ,[Attest aangepast]
      ,[Clausulering]
      ,[Datum uitreiking]
      ,[Basisonderwijs NL]
      ,[Omschrijving berekening]
      ,[Instelling]
      ,[Type evaluatie]
      ,[Aantal periodes]
      ,[Administratieve groep kort]
      ,[Administratieve groep volledig]
      ,[Domein]
      ,[Finaliteit]
      ,[LeerjaarInGraad]
      ,[Onderwijsvorm]
      ,[Soortleerjaar]
      ,[Stemcategorie]
      ,[Studiegebied]
      ,[Studierichting]
      ,[LeerjaarCijfer]
      ,[Schoolse achterstand]
      ,[Laatste login]
      ,[Aantal dagen geleden]
      ,[Wie laatst ingelogd]
      ,[Verschillende adressen]
      ,[Deelgemeente officieel adres]
      ,[Hoofdgemeente officeel adres]
      ,[Postcode officieel adres]
      ,[AF.']
      ,[AF.-]
      ,[AF.#]
      ,[AF..]
      ,[AF.?]
      ,[AF.+]
      ,[AF.°]
      ,[AF.1]
      ,[AF.2]
      ,[AF.3]
      ,[AF.4]
      ,[AF.5]
      ,[AF.6]
      ,[AF.7]
      ,[AF.8]
      ,[AF.9]
      ,[AF.0]
      ,[AF.A]
      ,[AF.B]
      ,[AF.C]
      ,[AF.D]
      ,[AF.E]
      ,[AF.F]
      ,[AF.G]
      ,[AF.H]
      ,[AF.I]
      ,[AF.J]
      ,[AF.K]
      ,[AF.L]
      ,[AF.M]
      ,[AF.N]
      ,[AF.O]
      ,[AF.P]
      ,[AF.Q]
      ,[AF.R]
      ,[AF.S]
      ,[AF.T]
      ,[AF.U]
      ,[AF.V]
      ,[AF.W]
      ,[AF.X]
      ,[AF.Y]
      ,[AF.Z]
      ,[AF.WE]
      ,[AF.VA]
      ,[AF.SV]
      ,[AF.ST]
      ,[AF.OL]
      ,[AF.KR]
      ,[AF.HL]
      ,[AF.H1]
      ,[AF.EX]
      ,[AF.WO]
      ,[AF.Totaal]
      ,[Vorige school]
      ,[Vorige klas]
      ,[Vorige loopbaan tot]
      ,[Lagere school]
      ,[Laaste leerjaar in lagere school]
      ,[Verandering klas tijdens schooljaar]
      ,[Zij-instromer school tijdens schooljaar]
      ,[Instroom in school bij begin schooljaar]
      ,[Intern]
      ,[Internaat]
      


  OPTION (Maxrecursion 0)