use WiseZonderFK

select 
	CONVERT(BINARY(64), hashbytes('SHA2_512', CONCAT('Korneel', CAST(EL.LL_ID AS VARCHAR(15))))) as hashID,
	MONTH(EL.GeboorteDatum) as Geboortemaand,
	YEAR(EL.GeboorteDatum) as Geboortejaar,
	EL.Geslacht,
	EL.Herkomst,
	EL.Nationaliteit,
	EL.Thuistaal,
	EL.Moedertaal,
	EL.[Beroep moeder],
	EL.[Beroep vader],
	EL.[Opleiding moeder],
	EL.[Burgelijke staat moeder],
	EL.[Burgelijke staat vader],
	EL.[Moeder overleden],
	EL.[Vader overleden],
	EL.[Nationaliteit moeder],
	EL.[Nationaliteit vader],
	EL.[Moeder - Nederlandstalig],
	EL.[Moeder - Franstalig],
	EL.[Moeder - Anderstalig (niet N/F)],
	EL.[Moeder - Geen info over taal],
	EL.[Vader - Nederlandstalig],
	EL.[Vader - Franstalig],
	EL.[Vader - Anderstalig (niet N/F)],
	EL.[Vader - Geen info over taal],
	EL.[Broer/zus - Nederlandstalig],
	EL.[Broer/zus - Franstalig],
	EL.[Broer/zus - Anderstalig (niet N/F)],
	EL.[Broer/zus - Geen info over taal],
	EL.[Vrienden - Nederlandstalig],
	EL.[Vrienden - Franstalig],
	EL.[Vrienden - Anderstalig (niet N/F)],
	EL.[Vrienden - Geen info over taal],
	EL.[Moeder - Lager onderwijs niet afgewerkt],
	EL.[Moeder - Lager onderwijs afgewerkt],
	EL.[Moeder - Lager secundair onderwijs afgewerkt],
	EL.[Moeder - Hoger secundair onderwijs afgewerkt],
	EL.[Moeder - Hoger onderwijs afgewerkt],
	EL.[Moeder - Laag geschoold],
	EL.[Thuistaal niet-Nederlands],
	ES.[Loopbaan van],
	ES.[Loopbaan tot],
	ES.[Datum uitschrijving],
    ES.[Klas],
    ES.[Schooljaar],
    ES.[Begin Schooljaar],
    ES.[Leerjaar],
    ES.[Graad],
    ES.[Andertalige nieuwkomer],
    ES.[Attest],
    ES.[Attest aangepast],
    ES.[Clausulering],
    ES.[Datum uitreiking],
    ES.[Basisonderwijs NL],
    ES.[Procent],
    ES.[Vak],
    ES.[Omschrijving berekening],
    ES.[Instelling],
    ES.[Type evaluatie],
    ES.[Aantal periodes],
    ES.[Administratieve groep kort],
    ES.[Administratieve groep volledig],
    ES.[Domein],
    ES.[Finaliteit],
    ES.[LeerjaarInGraad],
    ES.[Onderwijsvorm],
    ES.[Soortleerjaar],
    ES.[Stemcategorie],
    ES.[Studiegebied],
    ES.[Studierichting],
	SA.[LeerjaarCijfer],
    SA.[Schoolse achterstand],
	LI.[Laatste login],
    LI.[Aantal dagen geleden],
    LI.[Wie laatst ingelogd],
	AD.[Verschillende adressen],
    AD.[Deelgemeente officieel adres],
    AD.[Hoofdgemeente officeel adres],
    AD.[Postcode officieel adres],
	AF.['],
    AF.[-],
    AF.[#],
    AF.[*],
    AF.[.],
    AF.[?],
    AF.[+],
    AF.[°],
    AF.[1],
    AF.[2],
    AF.[3],
    AF.[4],
    AF.[5],
    AF.[6],
    AF.[7],
    AF.[8],
    AF.[9],
    AF.[0],
    AF.[A],
    AF.[B],
    AF.[C],
    AF.[D],
    AF.[E],
    AF.[F],
    AF.[G],
    AF.[H],
    AF.[I],
    AF.[J],
    AF.[K],
    AF.[L],
    AF.[M],
    AF.[N],
    AF.[O],
    AF.[P],
    AF.[Q],
    AF.[R],
    AF.[S],
    AF.[T],
    AF.[U],
    AF.[V],
    AF.[W],
    AF.[X],
    AF.[Y],
    AF.[Z],
    AF.[WE],
    AF.[VA],
    AF.[SV],
    AF.[ST],
    AF.[OL],
    AF.[KR],
    AF.[HL],
    AF.[H1],
    AF.[EX],
    AF.[WO],
    AF.[Totaal aantal halve dagen afwezig of laat],
	INS.[Vorige school],
    INS.[Vorige klas],
    INS.[Vorige loopbaan tot],
    INS.[Lagere school],
    INS.[Laaste leerjaar in lagere school],
    INS.[Verandering klas tijdens schooljaar],
    INS.[Zij-instromer school tijdens schooljaar],
    INS.[Instroom in school bij begin schooljaar],
	IT.[Intern],
	IT.[Internaat],
	ES.KL_CODE + '-' + CAST(ES.SJ_ID as varchar(15)) + '-' + CAST(ES.IV_ID as varchar(15)) + '-' + CAST(ES.IS_ID as varchar(15)) AS [koppeling leerkrachten]	
from [SJI - Vertrekpunt] VP -- 6616
inner join [SJI - Eigen aan leerling] EL on VP.LL_ID = EL.LL_ID -- 6616 
inner join [SJI - Eigen aan loopbaanitem] ES on VP.LL_ID = ES.LL_ID -- 54121
--inner join [SJI - Namen Leerlingen] NL on NL.LL_ID = EL.LL_ID --54121
left join [SJI - Schoolse achterstand] SA on SA.LB_ID = ES.LB_ID -- 54121
left join [SJI - Laatst ingelogd] LI on VP.LL_ID = LI.LL_ID -- 54121
left join [SJI - Adressen] AD on AD.LL_ID = VP.LL_ID -- 54121
left join [SJI - Afwezigheid] AF on ES.LB_ID = AF.LB_ID -- 54121
left join [SJI - Instroom] INS on ES.LB_ID = INS.LB_ID -- 54121
left join [SJI - Internaat] IT on IT.LL_ID = VP.LL_ID AND IT.SJ_ID = ES.SJ_ID  -- 54121
--left join [SJI - Leerkrachten_Diploma] LD on LD.KL_CODE = ES.KL_CODE AND LD.SJ_ID = ES.SJ_ID AND LD.IV_ID = ES.IV_ID AND LD.IS_ID = ES.IS_ID 


OPTION (MAXRECURSION 0)